// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBidRuicLbiJvlMpNhHho_glLKqpraX6Y',
    appId: '1:346761305197:web:161fd2475849170721f364',
    messagingSenderId: '346761305197',
    projectId: 'games-make-you-move-2025',
    authDomain: 'games-make-you-move-2025.firebaseapp.com',
    storageBucket: 'games-make-you-move-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0-Sccoe_S39xUmoHwvpldnnpZ2lCfrRg',
    appId: '1:346761305197:android:775d5ef2e52c96e321f364',
    messagingSenderId: '346761305197',
    projectId: 'games-make-you-move-2025',
    storageBucket: 'games-make-you-move-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBjgQZVkXHgF0WHvmIZF7jM3UG5DSJFHE',
    appId: '1:346761305197:ios:e3c007fc6585e69e21f364',
    messagingSenderId: '346761305197',
    projectId: 'games-make-you-move-2025',
    storageBucket: 'games-make-you-move-2025.firebasestorage.app',
    iosBundleId: 'com.tarekalabd.stepstracker.pedometer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBjgQZVkXHgF0WHvmIZF7jM3UG5DSJFHE',
    appId: '1:346761305197:ios:484a27ca35551db021f364',
    messagingSenderId: '346761305197',
    projectId: 'games-make-you-move-2025',
    storageBucket: 'games-make-you-move-2025.firebasestorage.app',
    iosBundleId: 'com.example.flutterStepsTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBidRuicLbiJvlMpNhHho_glLKqpraX6Y',
    appId: '1:346761305197:web:06e551b932adc3fa21f364',
    messagingSenderId: '346761305197',
    projectId: 'games-make-you-move-2025',
    authDomain: 'games-make-you-move-2025.firebaseapp.com',
    storageBucket: 'games-make-you-move-2025.firebasestorage.app',
  );
}
